language: groovy
jdk: oraclejdk8
before_install:
- chmod +x gradlew
script:
- ./gradlew clean build -PdisablePreDex --continue --stacktrace
branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: script
  script: ./gradlew bintrayUpload -PdryRun=false
  skip_cleanup: true
  on:
    tags: true
    branch: /^v\d+\.\d+\.\d+$/